---
title: "R Notebook"
author: fxy11
date: 10/9/2020
output: html_document
runtime: shiny
---

```{r}
library(shiny)
library(plotly)
library(shinythemes)
library(shiny)
library(shinydashboard)
library(leaflet)
library(shinyWidgets)
library(reshape2)
```

```{r}
ui <- dashboardPage(skin = "red",
                    dashboardHeader(title = "NYC Covid_19"),
                    dashboardSidebar(sidebarMenu(
                        menuItem("Home", tabName = "Home", icon = icon("home")),
                        menuItem("Animation", tabName = "Animation", icon = icon("train")),
                        menuItem("Map", tabName = "Map", icon = icon("map")),
                        menuItem("Report", tabName = "Report", icon = icon("industry"))
                    )),
                    dashboardBody(
                        tabItems(
                            #home
                          tabItem(tabName = "Map",
                                  fluidPage(
                                    leafletOutput("map",width="100%",height=750),
                                                  checkboxGroupInput("Borough", "Choose Borough:",
                                                                     choices = c("Manhattan", "Staten Island",
                                                                                 "Bronx", "Queens",
                                                                                 "Brooklyn"),
                                                                     selected = c("Manhattan", "Staten Island",
                                                                                  "Bronx", "Queens",
                                                                                  "Brooklyn")
                                                  ),

                                                  radioButtons("Category", "Choose category:",
                                                                choices = c("COVID_CASE_COUNT","COVID_DEATH_COUNT"))

                                  )
                          )
                        ))
)
```

```{r}
sum.formula <- JS("function(cluster) {
    var markers = cluster.getAllChildMarkers();
    var sum = 0;
    for (i = 0; i < markers.length; i++) {
      sum += Number(markers[i].options.mag);
    }
    var size = sum/10000
    var c = ' marker-cluster-';
      if (sum < 3000) {
        c += 'small';
      } else if (sum < 13000) {
        c += 'medium';
      } else {
        c += 'large';
      }
    return new L.DivIcon({ html: '<div><span>' + sum + '</span></div>', className: 'marker-cluster' + c, iconSize: L.point(size, size)});
  }")

server <- function(input, output) {

    na_drop <- read.csv("https://raw.githubusercontent.com/nychealth/coronavirus-data/master/data-by-modzcta.csv")
    na_drop <- melt(na_drop, id.vars=1:3, value.name="Count", variable.name="Category")
    zip_code <- read.csv('https://raw.githubusercontent.com/daling11/xxxxxxxx/master/zip_code_database.csv')
    colnames(zip_code)<-c('MODIFIED_ZCTA', 'lat', 'lon')
    na_drop <- merge(na_drop, zip_code, by='MODIFIED_ZCTA')
    #na_drop <- na_drop[which(na_drop$Category == "COVID_CASE_COUNT" | na_drop$Category == "COVID_DEATH_COUNT"),]
    #na_drop <- na_drop[rep(rownames(na_drop), na_drop$Count),]

    shiny_data <- reactive(na_drop[which(na_drop$Category %in% input$Category & na_drop$BOROUGH_GROUP %in% input$Borough),])

    output$map <- renderLeaflet({
      map<-leaflet(options = leafletOptions(minZoom = 8, maxZoom = 18)) %>%
      setView(-73.9252853, 40.7910694, zoom = 10) %>%
      addTiles() %>%
      addCircleMarkers(lng = shiny_data()$lon, lat = shiny_data()$lat, options = markerOptions(mag = shiny_data()$Count), color='red', stroke = FALSE, fillOpacity = 0.5,
                 clusterOptions = markerClusterOptions(iconCreateFunction=JS(sum.formula),
                                                       popup = paste("<b>", "Count", shiny_data()$Count, "<br/>", "<b>", "Borough:", shiny_data()$BOROUGH_GROUP)))%>%
       addProviderTiles(providers$CartoDB.Positron)%>%
        addLabelOnlyMarkers(lng = shiny_data()$lon, lat = shiny_data()$lat,
        options = markerOptions(mag = shiny_data()$Count),
        label =  shiny_data()$Count,
        labelOptions = labelOptions(noHide = T, direction = 'center', textOnly = T),
        clusterOptions = markerClusterOptions(iconCreateFunction=JS(sum.formula)))

  })
}
```

```{r echo = FALSE}
shinyApp(ui, server)
```

```{r}
na_drop <- read.csv("https://raw.githubusercontent.com/nychealth/coronavirus-data/master/data-by-modzcta.csv")
na_drop <- melt(na_drop, id.vars=1:3, value.name="Count", variable.name="Category")
zip_code <- read.csv('https://raw.githubusercontent.com/daling11/xxxxxxxx/master/zip_code_database.csv')
colnames(zip_code)<-c('MODIFIED_ZCTA', 'lat', 'lon')
na_drop <- merge(na_drop, zip_code, by='MODIFIED_ZCTA')
```

```{r}
na_drop <- na_drop[which(na_drop$Category == "COVID_CASE_COUNT" | na_drop$Category == "COVID_DEATH_COUNT"),]
na_drop <- na_drop[rep(rownames(na_drop), na_drop$Count),]
na_drop
```
```{r}
server <- function(input, output) {

  #na_drop <- na_drop[which(na_drop$Category == "COVID_CASE_COUNT" | na_drop$Category == "COVID_DEATH_COUNT"),]
  #na_drop <- na_drop[rep(rownames(na_drop), na_drop$Count),]

  shiny_data <- reactive(na_drop[which(na_drop$Category %in% input$Category & na_drop$BOROUGH_GROUP %in% input$Borough),])

  output$map <- renderLeaflet({
     leaflet(options = leafletOptions(minZoom = 8, maxZoom = 18)) %>%
      setView(-73.9252853, 40.7910694, zoom = 10) %>%
      addTiles() %>%
      addMarkers(data = shiny_data()$Count, lng = shiny_data()$lon, lat = shiny_data()$lat,
                 clusterOptions = markerClusterOptions(iconCreateFunction=JS(sum.formula))
      )
  })

  observe({
    df.marker <- shiny_data()
    leafletProxy("map", data = df.marker) %>%
      clearMarkerClusters()%>%
      clearPopups() %>%
      clearMarkers() %>%
      addMarkers(data = shiny_data()$Count, lng = shiny_data()$lon, lat = shiny_data()$lat,
                 popup = paste("<b>", "Count", shiny_data()$Count, "<br/>", "<b>", "Borough:", shiny_data()$BOROUGH_GROUP))
    clusterOptions <- markerClusterOptions()
  })
}
```
